name: xxtea
version: 2.1.0
description: XXTEA for Dart
  XXTEA is a fast and secure encryption algorithm. This is a XXTEA library for Dart.
homepage: https://github.com/xxtea/xxtea-dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: 'any'
